import { useEffect, useMemo, useState } from "react";
import {
  CircleDollarSign,
  Clock3,
  Coins,
  RefreshCw,
  Wallet,
} from "lucide-react";
import type { CommonProps } from "../../types";
import { writerRepository } from "../../features/writer";
import {
  apiWriterRepository,
  useApiWriterContent,
} from "../../services/repositories/writerRepository";

type EarningsSummary = {
  totalCoins: number;
  pendingCoins: number;
  availableCoins: number;
};

type EarningTransaction = {
  id: string;
  bookId: string;
  chapterId: string;
  coins: number;
  status: string;
  createdAt: string;
};

const formatCoins = (value: number) =>
  new Intl.NumberFormat("en-US", {
    maximumFractionDigits: 0,
  }).format(value);

const formatDate = (value: string) => {
  const date = new Date(value);

  if (Number.isNaN(date.getTime())) {
    return "Unknown date";
  }

  return new Intl.DateTimeFormat("en", {
    day: "numeric",
    month: "short",
    year: "numeric",
  }).format(date);
};

const statusLabel = (status: string) =>
  status
    .toLowerCase()
    .replace(/_/g, " ")
    .replace(/\b\w/g, (letter) => letter.toUpperCase());

export default function WriterEarnings({}: CommonProps) {
  const mockEarnings = writerRepository.getEarnings();

  const [summary, setSummary] = useState<EarningsSummary>({
    totalCoins: mockEarnings.grossEarnings,
    pendingCoins: mockEarnings.pending,
    availableCoins: mockEarnings.available,
  });

  const [transactions, setTransactions] = useState<EarningTransaction[]>([]);

  const [books, setBooks] = useState<Array<{ id: string; title: string }>>([]);

  const [loading, setLoading] = useState(useApiWriterContent);
  const [loadError, setLoadError] = useState("");

  useEffect(() => {
    if (!useApiWriterContent) {
      const mockBooks = writerRepository.getWriterBooks().map((book) => ({
        id: book.id,
        title: book.title,
      }));

      setBooks(mockBooks);

      return;
    }

    let cancelled = false;

    setLoading(true);
    setLoadError("");

    Promise.all([
      apiWriterRepository.getEarnings(),
      apiWriterRepository.getEarningTransactions(),
      apiWriterRepository.getWriterBooks(),
    ])
      .then(([earnings, transactionResult, writerBooks]) => {
        if (cancelled) return;

        setSummary(earnings);
        setTransactions(transactionResult.transactions ?? []);

        setBooks(
          writerBooks.map((book) => ({
            id: book.id,
            title: book.title,
          })),
        );
      })
      .catch((caught) => {
        if (cancelled) return;

        setLoadError(
          caught instanceof Error ? caught.message : "Unable to load earnings.",
        );
      })
      .finally(() => {
        if (!cancelled) {
          setLoading(false);
        }
      });

    return () => {
      cancelled = true;
    };
  }, []);

  const bookTitles = useMemo(
    () => new Map(books.map((book) => [book.id, book.title])),
    [books],
  );

  const mockTransactions = useMemo(
    () => [
      {
        id: "mock-1",
        bookId: "baobab-kingdom",
        chapterId: "baobab-kingdom-ch-3",
        coins: 620,
        status: "COMPLETED",
        createdAt: "2024-06-20T00:00:00.000Z",
      },
      {
        id: "mock-2",
        bookId: "echoes-of-kongo",
        chapterId: "echoes-of-kongo-ch-2",
        coins: 470,
        status: "PENDING",
        createdAt: "2024-06-18T00:00:00.000Z",
      },
      {
        id: "mock-3",
        bookId: "baobab-kingdom",
        chapterId: "baobab-kingdom-ch-3",
        coins: 310,
        status: "COMPLETED",
        createdAt: "2024-06-15T00:00:00.000Z",
      },
    ],
    [],
  );

  const visibleTransactions = useApiWriterContent
    ? transactions
    : mockTransactions;

  return (
    <div className="somi-writer-page">
      <div className="somi-writer-inner">
        <header className="somi-writer-header">
          <div>
            <p className="somi-writer-eyebrow">Writer Studio</p>

            <h1 className="somi-writer-title">Earnings</h1>

            <p className="somi-writer-description">
              Track the coins generated by your stories and monitor what is
              pending or currently available.
            </p>
          </div>

          <button
            type="button"
            className="somi-writer-secondary-action"
            onClick={() => window.location.reload()}
            disabled={loading}
          >
            <RefreshCw size={14} />
            Refresh
          </button>
        </header>

        {loadError && (
          <div className="somi-writer-notice">
            <p className="somi-writer-notice-title">
              Earnings could not be loaded
            </p>

            <p className="somi-writer-notice-text">{loadError}</p>
          </div>
        )}

        <section className="somi-writer-section">
          <div className="somi-c5-earnings-grid">
            <article className="somi-c5-earnings-primary">
              <div className="somi-c5-earnings-icon">
                <Coins size={19} />
              </div>

              <p className="somi-c5-earnings-label">Total earnings</p>

              <p className="somi-c5-earnings-value">
                {formatCoins(summary.totalCoins)}
              </p>

              <p className="somi-c5-earnings-unit">coins</p>
            </article>

            <article className="somi-c5-earnings-item">
              <Clock3 size={17} />

              <div>
                <p className="somi-c5-earnings-item-value">
                  {formatCoins(summary.pendingCoins)}
                </p>

                <p className="somi-c5-earnings-item-label">Pending coins</p>
              </div>
            </article>

            <article className="somi-c5-earnings-item">
              <Wallet size={17} />

              <div>
                <p className="somi-c5-earnings-item-value">
                  {formatCoins(summary.availableCoins)}
                </p>

                <p className="somi-c5-earnings-item-label">Available coins</p>
              </div>
            </article>
          </div>
        </section>

        <section className="somi-writer-section">
          <div className="somi-c5-section-heading">
            <div>
              <p className="somi-writer-eyebrow">Earnings activity</p>

              <h2 className="somi-c5-section-title">Recent earnings</h2>
            </div>

            <span className="somi-c5-section-meta">
              {useApiWriterContent ? "Live platform data" : "Demo data"}
            </span>
          </div>

          {loading ? (
            <div className="somi-c5-empty">Loading earnings…</div>
          ) : visibleTransactions.length === 0 ? (
            <div className="somi-c5-empty">
              <CircleDollarSign size={20} />

              <p>No earnings yet.</p>

              <span>
                Earnings from eligible chapter activity will appear here.
              </span>
            </div>
          ) : (
            <div className="somi-c5-transactions">
              {visibleTransactions.map((transaction) => (
                <article key={transaction.id} className="somi-c5-transaction">
                  <div className="somi-c5-transaction-main">
                    <p className="somi-c5-transaction-title">
                      {bookTitles.get(transaction.bookId) ?? transaction.bookId}
                    </p>

                    <p className="somi-c5-transaction-meta">
                      Chapter {transaction.chapterId}
                      {" · "}
                      {formatDate(transaction.createdAt)}
                    </p>
                  </div>

                  <div className="somi-c5-transaction-side">
                    <p className="somi-c5-transaction-coins">
                      +{formatCoins(transaction.coins)}
                    </p>

                    <span className="somi-c5-transaction-status">
                      {statusLabel(transaction.status)}
                    </span>
                  </div>
                </article>
              ))}
            </div>
          )}
        </section>

        <section className="somi-writer-section">
          <div className="somi-c5-insight">
            <div>
              <p className="somi-writer-eyebrow">SOMI economy</p>

              <h2 className="somi-c5-section-title">
                Your earnings are measured in SOMI coins.
              </h2>
            </div>

            <p>
              Pending coins represent earnings that have not yet become
              available. Available coins are the portion currently available to
              the writer according to the platform ledger.
            </p>
          </div>
        </section>
      </div>
    </div>
  );
}
